---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: archlinux
    image: docker.io/rwxd/archlinux-molecule:main
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
