---
- name: Install pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
  become: true
  when: > 
    ansible_distribution in ["Archlinux"]
    and pacman_packages is defined and pacman_packages | length > 0

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel
  when: >
    ansible_distribution in ["Archlinux"]
    and snap_packages is defined and snap_packages | length > 0

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  when: >
    ansible_distribution in ["Archlinux"]
    and snap_packages is defined and snap_packages | length > 0


- name: Install aur packages
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    state: present
  become: yes
  become_user: aur_builder
  when: >
    ansible_distribution in ["Archlinux"]
    and snap_packages is defined and snap_packages | length > 0

# - name: Install aur packages
#   command: "yay -S --aur --norebuild --answerclean No --answerdiff No {{ aur_packages | join(' ') }}"
#   when: ansible_distribution in ["Archlinux"]
#   register: output
#   changed_when: output.stdout != ""
#   loop: aur_packages

- name: Install snap packages
  community.general.snap:
    name: "{{ snap_packages }}"
  become: true
  when: snap_packages is defined and snap_packages | length > 0

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
  become: true
  when: flatpak_packages is defined and flatpak_packages | length > 0