---
- name: Install pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
  become: true
  when: ansible_distribution in ["Archlinux"]

- name: Install aur packages
  command: "yay -S --aur --norebuild --answerclean No --answerdiff No {{ aur_packages | join(' ') }}"
  when: ansible_distribution in ["Archlinux"]
  register: output
  changed_when: output.stdout != ""

- name: Install snap packages
  community.general.snap:
    name: "{{ snap_packages }}"
  become: true

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
  become: true
