---
- name: assure that tmux is installed
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: get the tmux plugin manager
  git:
    repo: git@github.com:tmux-plugins/tpm.git
    dest: "{{ lookup('env','HOME') }}/.tmux/plugins/tpm"
    version: master
    update: true
