---
- name: Run the equivalent of "pacman -Syu"
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true
  when: ansible_distribution in ["Archlinux"]

- name: Run the equivalent of "apt-get update"
  apt:
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]