---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu-20.04
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
