name: Molecule

on:
  push:
    branches:
      - main
      - release/v*

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: true 
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - archlinux
        python-version: ["3.9", "3.8", "3.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Molecule
        run: |
          molecule --debug test --scenario-name ${{ matrix.scenario }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: molecule
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: Install dependencies
        run: npm install semantic-release@18.0.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release